# Site wide configuration
title: "Peter Kirkham"
description: "Assorted reminisces and personal notes related to the oil and gas industry"
logo: 120x120logo.jpg # 120x120 px default image used for Twitter summary card
teaser: 400x250teaser.jpg  # 400x250 px default teaser image used in image archive grid
locale:
url: //pkirkham.github.io

# Jekyll configuration
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap

# Site owner
owner:
  name: "Peter Kirkham"
  email:
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: "Upstream jack-of-all-trades and master of some"
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
